# Site settings
author: Claudia Garcia 
title: “Why did you decide to study Software Engineering?”
header-img: img/home-bg.png
email: claudeegarcia@icloud.com
copyright_name: Claudia Garcia 
description: > # this means to ignore newlines until "baseurl:"
  It didn’t go where I expected
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Claudeegarcia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
